### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Darktreivor** [Giza/mgs3_gcx_editor#1]
Hello, can you explain how to use it?
When extracting text with gcx extract, it generates a CSV file. When opening this file with LibreOffice, it asks how I want to sort the file. I've tried in various ways, and sometimes I receive the error: "Index out of range" or "Hex sequence not found in binary file."

**Comment by Giza** [comment]
When extracting, a file with two columns is created, you need to add a 3rd column with new texts. 
`return [(row[0], row[1], row[2]) for row in reader]`
I don’t know if LibreOffice processes the file normally

**Comment by Darktreivor** [comment]
Thank you very much for your help, another question. Would it be possible to adapt it to do the same on the GCX of MGS2? I saw that there is a 'pattern' that in MGS3 would be 00001800000000, and in MGS2, it's 0014000000 or 14000000.
Using this pattern, I was able to extract, but I couldn't reimport. It shows the error 'Text count mismatch.

**Comment by Giza** [comment]
I didn't look at mgs2. There's probably a need to change the code in some places. And not just in one or two places.

**Comment by Darktreivor** [comment]
Sure, a question: what would I need to analyze to try to make it work in MGS2?

> I didn't look at mgs2. There's probably a need to change the code in some places. And not just in one or two places.

**Comment by criconhelp** [comment]
Firstly analyse the gcx files of mgs2 in a hex editor and understand how they differ from mgs3. Or another way is to find information describing the gcx format for mgs2.

**Comment by criconhelp** [comment]
> Sure, a question: what would I need to analyze to try to make it work in MGS2?
>
Firstly analyse the gcx files of mgs2 in a hex editor and understand how they differ from mgs3. Or another way to find information with description of gcx format for mgs2 and rewrite the script according to the format description.

**Comment by Giza** [comment]
> Thank you very much for your help, another question. Would it be possible to adapt it to do the same on the GCX of MGS2? I saw that there is a 'pattern' that in MGS3 would be 00001800000000, and in MGS2, it's 0014000000 or 14000000. Using this pattern, I was able to extract, but I couldn't reimport. It shows the error 'Text count mismatch.

added mgs2
